// resources/js/components/event-card.tsx
import Image from "next/image";
import { Event } from "@/app/evenements/event";

export default function EventCard({ event }: { event: Event }) {
  return (
    <a href={"/evenements/" + event.id}>
      <div className="w-[350px] h-[450px] bg-white m-4">
        <Image
          src={event.cover_image}
          alt="Image description"
          layout="responsive"
          width={500}
          height={500}
          style={{ maxHeight: "100%", width: "auto" }}
        />
        <h1 className="text-3xl text-center my-6">{event.title}</h1>
        <p className="text-xl px-3">Quand : {event.date}</p>
        <p className="text-xl px-3">Où : {event.location}</p>
        <p className="text-xl px-3">Pourquoi : {event.reason}</p>
      </div>
    </a>
  );
}

// resources/js/components/event-card.vue
<template>
    <a :href="'/evenement/' + event.id">
        <div className="m-4 h-[450px] w-[350px] bg-white">
            <img class="w-500 h-500" :src="event.cover_image" :alt="event.title" />
            <h1 className="my-6 text-center text-3xl">{{ event.title }}</h1>
            <p className="px-3 text-xl">Quand : {{ event.date }}</p>
            <p className="px-3 text-xl">Où : {{ event.location }}</p>
            <p className="px-3 text-xl">Pourquoi : {{ event.reason }}</p>
        </div>
    </a>
</template>

<script>
export default {
    props: {
        event: {},
    },
};
</script>

<style></style>
